#!/usr/bin/env bun
// Validation workflow for the resume PDF system (see GUIDE.md / PDF audit).
// Renders every template against representative fixtures — fresher,
// mid-level, dense senior, long-content stress test — and checks:
//   - one-page fit (or an honest report of why not)
//   - real, correctly-ordered extracted text (via pdftotext)
//   - expected section headings and contact info present
//   - no generator-identifying metadata (creator/producer)
// Exits non-zero if any check fails, so this can run as `bun run test`.
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import { execFileSync } from "child_process";
import { PDFDocument } from "pdf-lib";
import { PDF_TEMPLATES } from "../src/pdf/registry";
import { renderResumePdf } from "../src/pdf/render";
import { FIXTURES } from "./pdf-fixtures";

let failures = 0;
const workDir = mkdtempSync(join(tmpdir(), "devcard-pdf-test-"));

function check(condition: boolean, label: string) {
  console.log(`  ${condition ? "✓" : "✗ FAIL"}  ${label}`);
  if (!condition) failures++;
  return condition;
}

async function extractText(buffer: Buffer): Promise<string> {
  const pdfPath = join(workDir, `${crypto.randomUUID()}.pdf`);
  const txtPath = pdfPath.replace(/\.pdf$/, ".txt");
  writeFileSync(pdfPath, buffer);
  try {
    execFileSync("pdftotext", ["-layout", pdfPath, txtPath]);
    return readFileSync(txtPath, "utf8");
  } catch {
    return ""; // pdftotext unavailable — page-count/metadata checks still run
  }
}

async function main() {
  for (const { name: fixtureName, profile } of FIXTURES) {
    for (const template of PDF_TEMPLATES) {
      console.log(`\n=== ${template.id} :: ${fixtureName} ===`);

      const result = await renderResumePdf(template.id, profile);
      const doc = await PDFDocument.load(result.buffer);
      const text = await extractText(result.buffer);

      check(result.pageCount >= 1, `renders (${result.pageCount} page${result.pageCount === 1 ? "" : "s"}, density=${result.density})`);
      if (!result.fitOnePage) {
        console.log(`  ⚠ did not fit one page even at veryCompact — content genuinely exceeds one page`);
      }

      // Watermark / branding check
      const creator = doc.getCreator() ?? "";
      const producer = doc.getProducer() ?? "";
      check(!/react-pdf|generated by|ai-generated|chatgpt|openai|anthropic|claude/i.test(creator + producer + text), "no AI/tool branding in metadata or content");
      check(creator === "" && producer === "", `creator/producer metadata blank (got creator="${creator}", producer="${producer}")`);

      if (text) {
        const name = profile.profile?.name ?? "";
        check(text.includes(name), "candidate name appears in extracted text");
        if (profile.profile?.email) check(text.includes(profile.profile.email), "email appears in extracted text");
        if (profile.experiences.length > 0) check(text.includes("WORK EXPERIENCE"), 'has "WORK EXPERIENCE" heading');
        if (profile.skills.length > 0) check(text.includes("SKILLS"), 'has "SKILLS" heading');
        if (profile.education.length > 0) check(text.includes("EDUCATION"), 'has "EDUCATION" heading');

        // Reading-order sanity: name must extract before the first section
        // heading, and (when present) WORK EXPERIENCE before SKILLS —
        // catches the "scrambled by flexbox" failure mode directly.
        const nameIdx = text.indexOf(name);
        const expIdx = text.indexOf("WORK EXPERIENCE");
        const skillsIdx = text.indexOf("SKILLS");
        if (nameIdx >= 0 && expIdx >= 0) check(nameIdx < expIdx, "name extracts before WORK EXPERIENCE section");
        if (expIdx >= 0 && skillsIdx >= 0) check(expIdx < skillsIdx, "WORK EXPERIENCE extracts before SKILLS (reading order)");
      } else {
        console.log("  (pdftotext not available — skipped text-based checks)");
      }
    }
  }

  rmSync(workDir, { recursive: true, force: true });

  console.log(`\n${"=".repeat(50)}`);
  if (failures > 0) {
    console.log(`${failures} check(s) failed.`);
    process.exit(1);
  }
  console.log("All checks passed.");
}

main().catch((err) => {
  console.error("Fatal error running PDF validation:", err);
  process.exit(1);
});
