#!/usr/bin/env bun
// Validation workflow for the resume PDF system (see GUIDE.md / PDF audit).
// Renders every template against representative fixtures — fresher,
// mid-level, dense senior, long-content stress test — and checks:
//   - one-page fit (or an honest report of why not)
//   - real, correctly-ordered extracted text (via pdftotext)
//   - expected section headings and contact info present
//   - no generator-identifying metadata (creator/producer)
// Exits non-zero if any check fails, so this can run as `bun run test`.
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import { execFileSync } from "child_process";
import { PDFDocument } from "pdf-lib";
import { PDF_TEMPLATES } from "../src/pdf/registry";
import { renderResumePdf } from "../src/pdf/render";
import { applyResumeVersion } from "../src/pdf/tailor";
import { FIXTURES } from "./pdf-fixtures";

let failures = 0;
const workDir = mkdtempSync(join(tmpdir(), "devcard-pdf-test-"));

// Anchored to a standalone line so this matches a real section heading
// ("WORK EXPERIENCE" or sentence-case "Experience") without also matching
// the word inside prose (e.g. "3+ years of experience" in a summary).
const HEADING_RE = {
  experience: /^(?:work experience|experience)\s*$/im,
  skills: /^skills\s*$/im,
  education: /^education\s*$/im,
};

function headingIndex(text: string, re: RegExp): number {
  const m = re.exec(text);
  return m ? m.index : -1;
}

function check(condition: boolean, label: string) {
  console.log(`  ${condition ? "✓" : "✗ FAIL"}  ${label}`);
  if (!condition) failures++;
  return condition;
}

async function extractText(buffer: Buffer): Promise<string> {
  const pdfPath = join(workDir, `${crypto.randomUUID()}.pdf`);
  const txtPath = pdfPath.replace(/\.pdf$/, ".txt");
  writeFileSync(pdfPath, buffer);
  try {
    execFileSync("pdftotext", ["-layout", pdfPath, txtPath]);
    return readFileSync(txtPath, "utf8");
  } catch {
    return ""; // pdftotext unavailable — page-count/metadata checks still run
  }
}

async function main() {
  for (const { name: fixtureName, profile } of FIXTURES) {
    for (const template of PDF_TEMPLATES) {
      console.log(`\n=== ${template.id} :: ${fixtureName} ===`);

      // Same resolution every real render path goes through (no version —
      // see applyResumeVersion's comment on why this still matters even
      // then) so this test suite validates what production actually does.
      const result = await renderResumePdf(template.id, applyResumeVersion(profile));
      // updateMetadata: false — otherwise pdf-lib stamps its own Producer/
      // Creator into the in-memory parse just from loading it (even without
      // ever calling .save()), which would make this check a false
      // positive: it'd be reporting pdf-lib's own signature, not what's
      // actually in the bytes we serve to users.
      const doc = await PDFDocument.load(result.buffer, { updateMetadata: false });
      const text = await extractText(result.buffer);

      check(result.pageCount >= 1, `renders (${result.pageCount} page${result.pageCount === 1 ? "" : "s"}, density=${result.density})`);
      if (!result.fitOnePage) {
        console.log(`  ⚠ did not fit one page even at ultraCompact — content genuinely exceeds one page`);
      }

      // Watermark / branding check
      const creator = doc.getCreator() ?? "";
      const producer = doc.getProducer() ?? "";
      check(!/react-pdf|generated by|ai-generated|chatgpt|openai|anthropic|claude/i.test(creator + producer + text), "no AI/tool branding in metadata or content");
      check(creator === "" && producer === "", `creator/producer metadata blank (got creator="${creator}", producer="${producer}")`);

      if (text) {
        // Whitespace-normalized: a very long name legitimately wraps across
        // lines (pdftotext -layout renders that as a newline), which is
        // correct, uncorrupted text — an ATS parser normalizes whitespace
        // the same way when matching, so this compares the same way it does.
        const normalized = text.replace(/\s+/g, " ");
        const name = (profile.profile?.name ?? "").replace(/\s+/g, " ");
        check(normalized.includes(name), "candidate name appears in extracted text (whitespace-normalized)");
        if (profile.profile?.email) check(text.includes(profile.profile.email), "email appears in extracted text");
        if (profile.experiences.length > 0) check(HEADING_RE.experience.test(text), 'has an "Experience" heading');
        if (profile.skills.length > 0) check(HEADING_RE.skills.test(text), 'has a "Skills" heading');
        if (profile.education.length > 0) check(HEADING_RE.education.test(text), 'has an "Education" heading');

        // Reading-order sanity: name must extract before the first section
        // heading, and (when present) Skills before Experience — Polished
        // deliberately surfaces technical skills ahead of experience (see
        // templates/polished.tsx) — catches the "scrambled by flexbox"
        // failure mode directly.
        const nameIdx = text.indexOf(name);
        const skillsIdx = headingIndex(text, HEADING_RE.skills);
        const expIdx = headingIndex(text, HEADING_RE.experience);
        if (nameIdx >= 0 && skillsIdx >= 0) check(nameIdx < skillsIdx, "name extracts before Skills section");
        if (skillsIdx >= 0 && expIdx >= 0) check(skillsIdx < expIdx, "Skills extracts before Experience (reading order)");
      } else {
        console.log("  (pdftotext not available — skipped text-based checks)");
      }
    }
  }

  rmSync(workDir, { recursive: true, force: true });

  console.log(`\n${"=".repeat(50)}`);
  if (failures > 0) {
    console.log(`${failures} check(s) failed.`);
    process.exit(1);
  }
  console.log("All checks passed.");
}

main().catch((err) => {
  console.error("Fatal error running PDF validation:", err);
  process.exit(1);
});
